export * from './button';
export * from './pill';
export * from './mainStudentCard';
export * from './testimonialCard';
export * from './pageText';
export * from './sectionText';
export * from './accordian';
export * from './ourbatchesCard';
export * from './otherStudentCard'
export * from './PageEndingText';
export * from './policyText';
export * from './careerGuidanceText';
export * from './ourBatchesPage';
export * from './highlightedStudentCard';